%% Job 2: generate coarse maps

useParallel = true; % run in parallel (requires more RAM and parallel computing toolbox)

%%
% Filter, Integrate, and Correct

workingDir = fullfile('proc',...
   {'7_1','8_1','8_2','8_3','9_1','9_2',...
   '10_1','10_2','10_3','10_6','10_7'});
%%
opts = struct(...
    'workingDirectory',workingDir,...
    'ndiv',[5,5,5],...  % this choice impacts speed to a large extent
    'window',2,...
    'maxCount',20,...
    'smax',Inf,...
    'binMode','coarse',...
    'minimumCounts',10,...
    'minimumPixels',10,...
    'parallel',useParallel,...
    'binExcludedVoxels',true...  % treats excluded voxels as Bragg peaks
    );

% assign run options
for j=1:length(opts)
    opts(j).run = {'filter','integrate','correct','export'};
end

[tf,EM] = proc.Batch.autorun(opts);

%% combine wedges

exportIn = fullfile({'7_1','8_1','8_2','8_3','9_1','9_2',...
    '10_1','10_2','10_3','10_6','10_7'},'export.mat');

[tf,EM] = proc.Batch.combine(...
    'workingDirectory','proc',...
    'exportIn',exportIn,...
    'combineBragg',true,...
    'mergeNeighbors',true);
